[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
rpc_endpoints = { mainnet = "https://rpc.ankr.com/eth" , bsc = "https://rpc.ankr.com/bsc"  , goreli = "https://rpc.ankr.com/eth_goerli" , arb = "https://rpc.ankr.com/arbitrum" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config